---
# Credentials profile name from your ~/.aws/credentials file
profile_name: my-profile-name

# assertions
assertions:
  regions:
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - eu-west-3
    - ca-central-1
  services:
    - ec2
    - natgateway
#    - rds
  output_format: "csv" # csv or json

# End ;
